In [8]:
import os
import pandas as pd
os.chdir('/Users/amawest/Desktop/')
circuit = pd.read_csv("circuit_criminal_2019.csv")

In [21]:
circuit[['Charge','CodeSection']].head(5)

                           Charge CodeSection
0       VIOL PROBATION ON FEL OFF    19.2-306
1       GRAND LARCENY: AUTO THEFT     18.2-95
2  ENTER HOUSE TO COMMIT A&B ETC.     18.2-91
3      DRUGS: POSSESS SCH I OR II    18.2-250
4               SHOW CAUSE MOTION    18.2-456

In [11]:
len(circuit.CodeSection.unique())

787

In [13]:
# This simply creates a copy of the charge and charge code, 
# drops duplicates and keeps the first instance of the charge description.
# because there are SO many different charge codes, we are just using the 
# first instance, but it would be more accurate to go and manually label all of the 
# charge codes to be the most accurate.
x = circuit[['Charge', 'CodeSection']].drop_duplicates(subset='CodeSection', keep="last")
x = x.rename(columns={"Charge": "CodeSection_Description"})
x

              CodeSection_Description   CodeSection
17           PROBATION VIOLATION-MISD      53.1-149
167              TEXTING IN WORK ZONE   46.2-1078.1
301    SCH BUS FLASH LIGHTS; NOT STOP      46.2-859
548      TRANPORT LOADED RIFLE IN VEH          10-4
885     DIST IMITAT CONT SUB SCH I-IV  18.2-248 (G)
...                               ...           ...
78115      CONSPIRACY TO COMMIT B & E       18.2-91
78117         CONTEMPT-FAIL TO APPEAR      18.2-456
78118           DWI: 3RD OFF W/IN 5YR    C.18.2-266
78119          ELUDE/DISREGARD POLICE   46.2-817(B)
78120                             NaN           NaN

[787 rows x 2 columns]

In [22]:
# Now we merge the data back together, with "CodeSection_Description"
# being 1:1 with each charge code (versus there being many "charge" instances for each charge code)
result = pd.merge(x, circuit, on="CodeSection")
result

,CodeSection_Description,CodeSection,HearingDate,HearingResult,HearingJury,HearingPlea,HearingType,HearingRoom,fips,Filed,...,DrivingRestrictions,RestrictionEffectiveDate,RestrictionEndDate,VAAlcoholSafetyAction,RestitutionPaid,RestitutionAmount,Military,TrafficFatality,AppealedDate,person_id
0,PROBATION VIOLATION-MISD,53.1-149,2019-09-17,Sentenced,NaN,NaN,Revocation,NaN,91,2019-08-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.512000e+13
1,PROBATION VIOLATION-MISD,53.1-149,2019-03-04,Revoked - Sentence/Probation,NaN,NaN,Revocation,NaN,91,2017-09-11,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,f,NaN,2.380200e+14
2,PROBATION VIOLATION-MISD,53.1-149,2019-03-04,Dismissed,NaN,NaN,Review,NaN,91,2018-01-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.922100e+13
3,TEXTING IN WORK ZONE,46.2-1078.1,2019-11-26,Sentenced,NaN,Tried In Absentia,Sentencing,NaN,99,2019-08-01,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,1.430300e+14
4,SCH BUS FLASH LIGHTS; NOT STOP,46.2-859,2019-09-26,Sentenced,NaN,Guilty,Trial,NaN,99,2019-05-09,...,t,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.311800e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78116,NaN,NaN,2019-01-22,Resolved,NaN,NaN,Show Cause,NaN,175,2018-11-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,1.017100e+13
78117,NaN,NaN,2019-01-22,Resolved,NaN,NaN,Show Cause,NaN,175,2018-10-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.002000e+13
78118,NaN,NaN,2019-01-22,Resolved,NaN,NaN,Show Cause,NaN,175,2018-10-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.002000e+13
78119,NaN,NaN,2019-01-02,Show Cause Issued,NaN,NaN,Show Cause,NaN,175,2019-01-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.401000e+13
78120,NaN,NaN,2019-05-07,Judgment Entered (Fines & Costs),NaN,NaN,Trial,NaN,63,2019-01-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
pwd

'/Users/amawest/Desktop'