## Question 6
- What are the most common offenses in the VA court system?

**Issues:**
- Add most common for black folks, white folks, minorities separately.

In [1]:
import io
import os
import requests
import numpy as np
import pandas as pd
from pyspark.sql import SparkSession
import matplotlib as plt
import seaborn as sns

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-5tg3qlpj because the default path (/home/jovyan/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

In [6]:
infile = 'Data/circuit_criminal_2019.csv'
spark = SparkSession \
    .builder \
    .appName("Criminal Expungement") \
    .getOrCreate()
circuit = spark.read.csv(infile, inferSchema=True, header = True)
circuit.createOrReplaceTempView('court_data')

In [11]:
sqlDF = spark.sql('SELECT Charge, CodeSection, count(Charge) as Count FROM court_data \
                   GROUP BY Charge, CodeSection ORDER BY Count DESC')
df = sqlDF.toPandas().head(20)
df.rename(columns={"Charge": "Individual Charge", "CodeSection": "CodeSection (May Repeat)"})

                 Individual Charge CodeSection (May Repeat)  Count
0        VIOL PROBATION ON FEL OFF                 19.2-306   7064
1                      BOND APPEAL                 19.2-124   1531
2              PROBATION VIOLATION                 19.2-306   1439
3     POSS.OF CONTROLLED SUBSTANCE                 18.2-250   1421
4                    GRAND LARCENY                  18.2-95   1004
5       VIOL PROBATION OF MISD OFF                 19.2-306    875
6            SHOW CAUSE REVOCATION                 19.2-306    820
7       DRUGS: POSSESS SCH I OR II                 18.2-250    771
8   OBTAIN MONEY FALSE PRET >=$200                 18.2-178    717
9             CAPIAS TO SHOW CAUSE                 19.2-306    699
10                         FORGERY                 18.2-172    664
11  MANUF/ETC CONTROLLED SUBSTANCE                 18.2-248    654
12  BAIL-APPEAL CONDITN OF RELEASE                 19.2-124    569
13   POSS SCH I/II CONTR SUBSTANCE                 18.2-250    558
14                        UTTERING                 18.2-172    521
15        FAIL TO APPEAR; CONTEMPT                 18.2-456    492
16              MALICIOUS WOUNDING                  18.2-51    492
17       POSS SCH I OR II CONT SUB                 18.2-250    424
18         POSSESSION OF MARIJUANA               18.2-250.1    419
19  FAIL TO APPEAR, FELONY OFFENSE                 19.2-128    417